# This is a basic workflow to help you get started with Actions

name: Deploy API

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        # username
        username: ${{ secrets.PI_USERNAME }}
        # your sftp server
        server: ${{ secrets.PI_HOST }}
        # your sftp server port, default to 22
        port: ${{ secrets.PI_PORT }}
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{ secrets.SSH_KEY_PI }}
        # will put all file under this path
        local_path: ./api/*
        # files will copy to under remote_path
        remote_path: /home/thomasc/volunity/api/
